# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Artists', models.CharField(max_length=200)),
                ('Album_Name', models.CharField(max_length=200)),
                ('Created_Date', models.DateTimeField(verbose_name='auto_now_add=True')),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Email_ID', models.CharField(max_length=100)),
                ('Phone_Number', models.IntegerField(verbose_name=12)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Allowed_Flag', models.CharField(max_length=100)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canticle.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canticle.User'),
        ),
    ]
