# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canticle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Artists', models.CharField(max_length=200)),
                ('Album_Name', models.CharField(max_length=200)),
                ('Created_Date', models.DateTimeField(verbose_name='auto_now_add=True')),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='website_information',
            name='Link',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Website_Information',
        ),
    ]
